services:
  app:
    image: ghcr.io/sidneyjfg/monitoramento_automatico_plugg:1.0
    container_name: monitoramento_automatico_pluggto
    restart: unless-stopped
    environment:
      - PORT=${PORT}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
      - GOOGLE_CHAT_WEBHOOK_URL=${GOOGLE_CHAT_WEBHOOK_URL}
      - PLUGGTO_CLIENT_ID=${PLUGGTO_CLIENT_ID}
      - PLUGGTO_CLIENT_SECRET=${PLUGGTO_CLIENT_SECRET}
      - PLUGGTO_USERNAME=${PLUGGTO_USERNAME}
      - PLUGGTO_PASSWORD=${PLUGGTO_PASSWORD}
      - PLUGGTO_URL=${PLUGGTO_URL}
      - DAYS_TO_FETCH=${DAYS_TO_FETCH}
      - TZ=${TZ}
    ports:
      - "${PORT}:3003"
